version: "4"
services:
  mailhog:
    container_name: fakeSMTP-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"